name: Calculate Database

on:
  workflow_dispatch:

jobs:
  calculate:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Calculate Database
      run: |
        set -euo pipefail
        git config --global user.email "theypsilon@gmail.com"
        git config --global user.name "The CI/CD Bot"
        rm db.json.zip
        ./.github/calculate_db.py
      env:
        DB_ID: distribution_mister
        DB_URL: https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/main/db.json.zip
        BASE_FILES_URL: https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/%s/
        LATEST_ZIP_URL: https://github.com/MiSTer-devel/Distribution_MiSTer/archive/refs/heads/main.zip
        LINUX_GITHUB_REPOSITORY: MiSTer-devel/SD-Installer-Win64_MiSTer
