name: Update Distribution

on:
  schedule:
  - cron:  "*/20 * * * *"
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-20.04

    steps:
    - name: Install apt-get utilities
      run: sudo apt-get install detox sharutils

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - uses: actions/checkout@v2
      with:
        ref: develop

    - name: Grab Dependencies
      run: |
        set -euo pipefail
        cd .github
        
        curl -o zips_config.json "https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/develop/.github/zips_config.json"
        curl -o download_distribution.py "https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/develop/.github/download_distribution.py"
        curl -o commit_distribution.sh "https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/develop/.github/commit_distribution.sh"
        curl -o calculate_db.py "https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/develop/.github/calculate_db.py"
        curl -o requirements.txt "https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/develop/.github/requirements.txt"
        
        chmod +x download_distribution.py commit_distribution.sh calculate_db.py

    - run: pip install -r .github/requirements.txt

    - name: Download Distribution
      run: |
        cd .github
        ./download_encc_distribution.py ..

    - name: Commit Distribution
      run: ./.github/commit_distribution.sh
      
    - name: Update Distribution
      run: |
        set -euo pipefail
        git config --global user.email "theypsilon@gmail.com"
        git config --global user.name "The CI/CD Bot"

        export DB_ID=distribution_mister
        export DB_URL=https://raw.githubusercontent.com/MiSTer-DB9/Distribution_MiSTer/main/dbencc.json.zip
        export BASE_FILES_URL=https://raw.githubusercontent.com/MiSTer-DB9/Distribution_MiSTer/%s/
        export LATEST_ZIP_URL=https://github.com/MiSTer-DB9/Distribution_MiSTer/archive/refs/heads/main.zip
        export ZIPS_CONFIG=./.github/zips_config.json
        export LINUX_GITHUB_REPOSITORY=MiSTer-devel/SD-Installer-Win64_MiSTer

        ./.github/calculate_db.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
